# Generated by Django 4.1.4 on 2023-04-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(blank=True, max_length=255)),
                ("email", models.CharField(max_length=255, null=True)),
                ("gender", models.BooleanField(null=True)),
                ("date", models.DateField(null=True)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255, null=True)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
